version: "2"

services:
    app:
        build: "./"
        volumes:
            - "./docker/apache/config/sites-available:/etc/apache2/sites-available"
            - "./docker/apache/logs:/var/log/apache2"
            - "./:/var/www/mvhost"
        ports:
            - "80:80"
            - "443:443"
        pid: "host"
        networks:
            appnet:
                ipv4_address: "192.168.1.10"

networks:
    appnet:
        driver: "bridge"
        ipam:
            driver: "default"
            config:
                - subnet: "192.168.1.0/24"
